import numpy as np
import pickle

#global values
L       = 1              #meters
Natoms  = 400           
Ratom   = 0.03           #meters
T       = 300            #Kelvin (K)
k_b     = 1.4e-23        #J/K
dt      = 1e-5           #seconds
N_A     = 6.0221408e+23
He_mm   = 4e-3           #kilograms/mole
He_mass = He_mm/N_A      #kilograms

def initialize_atoms():
    poss     = L*(np.random.rand(Natoms,3)-0.5)
    vel_mag  = np.sqrt(3*k_b*T/He_mass)
    thetas   = np.pi*np.random.rand(Natoms)
    phis     = 2*np.pi*np.random.rand(Natoms)
    vels     = vel_mag*np.array([np.sin(thetas)*np.cos(phis),np.sin(thetas)*np.sin(phis),np.cos(thetas)]).T #verified by hand
    return poss, vels

poss, vels = initialize_atoms()

sim_meta_data = '''
  Generated by Initialize_Particles_for_Simulation.  Generates as standard test set of 
  Maxwell hard spheres for use in the various algorithms.
'''
sim_name = 'Init_Atoms'

data = {'positions':poss, 'velocities': vels, 'meta_data':'sim_meta_data','name':sim_name}

fileObj = open('initialized_atoms.pkl', 'wb')
pickle.dump(data,fileObj)
fileObj.close()
